# Generated by Django 4.0.5 on 2022-07-04 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoxBachelor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('link', models.URLField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('date_deleted', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='meeting',
            name='image',
            field=models.ImageField(default='IMG', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meeting',
            name='price',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sitecontact',
            name='_copyright',
            field=models.CharField(default='Popo city', max_length=150, verbose_name='copyright'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='url_link_youtube',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='videowelcome',
            name='video',
            field=models.FileField(default='Popo video', upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='banner',
            name='date_deleted',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='faq',
            name='date_deleted',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='date_deleted',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='meetingcategory',
            name='date_deleted',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='popularcourses',
            name='date_deleted',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='sitecontact',
            name='date_deleted',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='universitystatistic',
            name='date_deleted',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='date_deleted',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='videowelcome',
            name='date_deleted',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='welcometext',
            name='date_deleted',
            field=models.BooleanField(default=True),
        ),
    ]
